spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/route_finder_db
    username: route_user
    password: route_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
