spring:
  application:
    name: ingestor
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/route_finder_db}
    username: ${DB_USER:route_user}
    password: ${DB_PASSWORD:route_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  main:
    web-application-type: none


budatravel:
  gtfs:
    source: ${GTFS_SOURCE:demo}
    demo:
      resource: ${GTFS_DEMO_RESOURCE:classpath:gtfs/budapest-mini.zip}
    local-file:
      path: ${GTFS_ARCHIVE_PATH:}
    bkk-remote:
      url: ${BKK_GTFS_URL:}
      api-key: ${BKK_API_KEY:}
      cache-dir: ${BKK_GTFS_CACHE_DIR:/tmp/budatravel/gtfs-cache}
