spring:
  application:
    name: ingestor
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/route_finder_db}
    username: ${DB_USER:route_user}
    password: ${DB_PASSWORD:route_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  main:
    web-application-type: none
